version: '3.2'

services:
  api-local:
    image: webdev00/lister-api:latest
    build:
      context: .
    ports: 
      - 80:80
    volumes:
      - ./:/var/www/html
      
  db-local:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $LOCAL_DB_ROOT_PASSWORD
    volumes: 
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3307:3306

  adminer:
    image: adminer
    restart: always
    ports: 
      - 8082:8080

volumes: 
  mysql-data:
