version: '3.2'

services:
  php:
    image: webdev00/lister-api:latest
    build:
      context: .
    ports: 
      - 80:80
      
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes: 
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports: 
      - 8080:8080

volumes: 
  mysql-data:
