version: '3.2'

services:
  php:
    image: webdev00/php-project_php:latest
    ports: 
      - 80:80
#    volumes: 
#      - ./:/var/www/html
      
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes: 
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports: 
      - 8080:8080
volumes: 
  mysql-data:
